#!/usr/bin/env python3
"""Decompose recognized diff_pair / current_mirror groups out of a flat
SPICE netlist into their own named `.subckt` blocks, and rewrite the
top-level circuit to instantiate them with a single X-line each -- every
OTHER net name and device line in the top-level circuit is left exactly
as it was (untouched, same names, same position, same params).

Topology recognition reuses `../../sub-layout-handler/script/
detect_topology.py`'s own `parse_devices()`/`detect()` (the same
drain/gate/source signature matching `generate_primitives.py` already
relies on for layout generation) -- this script does the analogous thing
one level up, at the SCHEMATIC text level, with no PDK/layout/Component
involved. Only `current_mirror` and `differential_pair` findings are
decomposed (those are the two topologies with a dedicated glayout module
and an established `.subckt` pin-naming convention to match --
`cells/diff_pair.py`'s `diff_pair_netlist()` and `cells/current_mirror.py`'s
`current_mirror_netlist()`); anything else `detect()` finds (transmission
gate, FVF, quad pair, cascode mirror) is reported but left as raw devices
at the top level, and so is everything `detect()` never classifies
(single-device stages, R/C passives).

Unlike `diff_pair_netlist()`/`current_mirror_netlist()` (which wrap each
device in a `.info['netlist']` Netlist object generated by actually
building an `nmos()`/`pmos()` glayout Component -- overhead that exists
because those need to describe the DUMMY-inclusive, physically-extracted
version of the device for LVS), this script has no Component/PDK
involved -- there's no dummy in a schematic-level netlist -- so each
decomposed device keeps its ORIGINAL instance name/model/params line
verbatim, with only its net tokens rewritten to the new pin names.

Pin-naming convention (matches the layout-side generators exactly, so a
decomposed sub-circuit's pin list reads the same way a human already
knows from `cells/diff_pair.py`/`cells/current_mirror.py`):
  differential_pair: VP VN diff_M1_drain diff_M2_drain VTAIL B
  current_mirror:    drain_ref VOUT[i...] <VSS|VDD> source_ref Out[i]_source...
    (bulk rail name is VDD for a pfet mirror, VSS for an nfet one -- see
    `bulk_rail_name()`, mirrors `current_mirror.py`'s own
    `rail_name_for_device()`; VOUT/VOUT1/VOUT2/... follows
    `current_mirror_netlist()`'s own single-vs-multi-branch convention)

Usage:
  python decompose_netlist.py path/to/design.sp
      [--subckt NAME] [--out-dir path/to/out] [--topologies current_mirror,differential_pair]

`--subckt` disambiguates which `.subckt` block to decompose if the file
defines more than one (default: the only one, or the whole file if none
of it is wrapped in a `.subckt`/`.ends` at all). Writes one `.sp` file per
decomposed group (`<out-dir>/<subckt_name>.sp`) plus the rewritten
top-level netlist (`<out-dir>/<original filename>`) that `.include`s them
-- never overwrites the input file in place (see `../../../../CLAUDE.md`'s
"Key Rules": a netlist already in the post-layout loop is frozen; this
tool always writes to a separate `--out-dir`, leaving that judgment call
to whoever runs it)."""
import argparse
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
SKILLS_DIR = SCRIPT_DIR.parent.parent
sys.path.insert(0, str(SKILLS_DIR.parent / "reference"))
import detect_topology as topo  # noqa: E402


def bulk_rail_name(kind: str) -> str:
    """Mirrors `cells/current_mirror.py`'s own `rail_name_for_device()`."""
    return "VDD" if kind == "pfet" else "VSS"


def read_joined_lines(filepath: str) -> list[str]:
    """Line-continuation-merged raw lines (a `+`-prefixed line is folded
    into the previous one), same convention `detect_topology.parse_devices()`
    uses -- kept as a parallel pass here (not imported) because this one
    needs to preserve each line's exact original text, not just parse it."""
    with open(filepath) as f:
        lines = f.read().splitlines()
    joined = []
    for line in lines:
        if line.strip().startswith('+') and joined:
            joined[-1] += ' ' + line.strip()[1:]
        else:
            joined.append(line)
    return joined


def device_line_index(joined: list[str]) -> dict[str, int]:
    """name -> index into `joined` of that MOSFET's own device line (reuses
    `detect_topology`'s own device-line regex so a line counts as "this
    device's line" under the exact same rule the topology scan used)."""
    idx = {}
    for i, line in enumerate(joined):
        m = topo._MOS_MODEL_RE.match(line)
        if m:
            idx[m.group('name')] = i
    return idx


def substitute_nets(line: str, new_nets: list[str]) -> str:
    """Replaces a device line's net tokens with `new_nets`, keeping the
    instance name, model, and every parameter (w=, l=, m=, ...) exactly as
    originally written -- no reformatting, no precision loss."""
    m = topo._MOS_MODEL_RE.match(line)
    name = m.group('name')
    model = m.group('model')
    params = m.group('params').strip()
    tail = f" {params}" if params else ""
    return f"{name} {' '.join(new_nets)} {model}{tail}"


def find_subckt_bounds(joined: list[str], subckt_name: str | None) -> tuple[int, int, list[str]]:
    """Returns (header_line_index, ends_line_index, pins) for the `.subckt`
    block to decompose, or (-1, len(joined), []) if the file has no
    `.subckt`/`.ends` at all (a bare flat device list is decomposed as-is,
    top-level pin list left empty since there's nothing to preserve)."""
    header_idx = None
    for i, line in enumerate(joined):
        stripped = line.strip()
        if stripped.lower().startswith('.subckt'):
            tokens = stripped.split()
            name = tokens[1] if len(tokens) > 1 else None
            if subckt_name is None or name == subckt_name:
                header_idx = i
                pins = tokens[2:]
                break
    if header_idx is None:
        if subckt_name is not None:
            raise ValueError(f".subckt {subckt_name} not found in netlist")
        return -1, len(joined), []
    for j in range(header_idx + 1, len(joined)):
        if joined[j].strip().lower().startswith('.ends'):
            return header_idx, j, pins
    raise ValueError(f".subckt at line {header_idx + 1} has no matching .ends")


def build_diff_pair_subckt(idx: int, a: dict, b: dict) -> tuple[str, list[str], list[str], dict, list[str]]:
    """Returns (subckt_name, device_name_order, pins, {device_name: new_net_list},
    top_level_nets_in_pin_order)."""
    if a['source'] != b['source']:
        raise ValueError(f"diff pair {a['name']}/{b['name']}: sources differ ({a['source']} != {b['source']})")
    if (a['bulk'] or b['bulk']) and a['bulk'] != b['bulk']:
        raise ValueError(f"diff pair {a['name']}/{b['name']}: bulks differ ({a['bulk']} != {b['bulk']})")
    name = f"DIFF_PAIR_{idx}"
    pins = ["VP", "VN", "diff_M1_drain", "diff_M2_drain", "VTAIL", "B"]
    device_nets = {a['name']: ["diff_M1_drain", "VP", "VTAIL", "B"], b['name']: ["diff_M2_drain", "VN", "VTAIL", "B"]}
    top_nets = [a['gate'], b['gate'], a['drain'], b['drain'], a['source'], a['bulk']]
    return name, [a['name'], b['name']], pins, device_nets, top_nets


def build_current_mirror_subckt(idx: int, ref: dict, mirrors: list[dict]) -> tuple[str, list[str], list[str], dict, list[str]]:
    for m in mirrors:
        if m['bulk'] != ref['bulk']:
            raise ValueError(f"current mirror ref {ref['name']}: bulk mismatch on mirror {m['name']} "
                              f"({m['bulk']} != {ref['bulk']})")
    rail = bulk_rail_name(ref['kind'])
    n = len(mirrors)
    out_nets = ["VOUT"] if n == 1 else [f"VOUT{i + 1}" for i in range(n)]
    source_rail_names = ["source_ref"] + [f"Out{i + 1}_source" for i in range(n)]
    pins = ["drain_ref", *out_nets, rail, *source_rail_names]
    name = f"CURRENT_MIRROR_{idx}"

    device_order = [ref['name']] + [m['name'] for m in mirrors]
    device_nets = {ref['name']: ["drain_ref", "drain_ref", "source_ref", rail]}
    top_by_pin = {"drain_ref": ref['drain'], rail: ref['bulk'], "source_ref": ref['source']}
    for i, m in enumerate(mirrors):
        out_net, src_pin = out_nets[i], source_rail_names[i + 1]
        device_nets[m['name']] = [out_net, "drain_ref", src_pin, rail]
        top_by_pin[out_net] = m['drain']
        top_by_pin[src_pin] = m['source']
    top_nets = [top_by_pin[p] for p in pins]
    return name, device_order, pins, device_nets, top_nets


def decompose(netlist_path: str, subckt_name: str | None, topologies: set[str]) -> dict:
    devices = topo.parse_devices(netlist_path)
    if not devices:
        raise ValueError(f"no MOSFET/BJT device lines found in {netlist_path}")
    findings, unclassified = topo.detect(devices)
    dev_by_name = {d['name']: d for d in devices}

    joined = read_joined_lines(netlist_path)
    dev_line_idx = device_line_index(joined)
    header_idx, ends_idx, top_pins = find_subckt_bounds(joined, subckt_name)

    groups = []  # list of dicts: name, body_lines(text), pins, top_nets, device_names
    consumed_line_idx = set()
    dp_i = cm_i = 0
    skipped_topologies = set()
    for finding in findings:
        # Only decompose groups whose devices are actually inside the
        # .subckt block we're rewriting (relevant if the file has other,
        # unrelated .subckt blocks the caller didn't select).
        if header_idx != -1 and any(not (header_idx < dev_line_idx.get(d, -1) < ends_idx) for d in finding['devices']):
            continue
        if finding['topology'] == 'differential_pair' and 'differential_pair' in topologies:
            dp_i += 1
            a, b = dev_by_name[finding['devices'][0]], dev_by_name[finding['devices'][1]]
            name, order, pins, device_nets, top_nets = build_diff_pair_subckt(dp_i, a, b)
        elif finding['topology'] == 'current_mirror' and 'current_mirror' in topologies:
            cm_i += 1
            ref = dev_by_name[finding['devices'][0]]
            mirrors = [dev_by_name[d] for d in finding['devices'][1:]]
            name, order, pins, device_nets, top_nets = build_current_mirror_subckt(cm_i, ref, mirrors)
        else:
            if finding['topology'] not in ('differential_pair', 'current_mirror'):
                skipped_topologies.add(finding['topology'])
            continue

        body = [substitute_nets(joined[dev_line_idx[dname]], device_nets[dname]) for dname in order]
        groups.append({'name': name, 'body': body, 'pins': pins, 'top_nets': top_nets, 'devices': order})
        consumed_line_idx.update(dev_line_idx[d] for d in order)

    # Rebuild the top-level block: first consumed line of a group becomes
    # the X-instance call, later lines in the same group are dropped,
    # everything else (comments, blank lines, untouched devices) passes
    # through unchanged.
    first_line_of_group = {min(dev_line_idx[d] for d in g['devices']): g for g in groups}
    dropped_lines = consumed_line_idx - set(first_line_of_group.keys())

    out_lines = []
    for i, line in enumerate(joined):
        if i in dropped_lines:
            continue
        if i in first_line_of_group:
            g = first_line_of_group[i]
            out_lines.append(f"X{g['name']} {' '.join(g['top_nets'])} {g['name']}")
            continue
        out_lines.append(line)

    return {
        'groups': groups,
        'top_level_lines': out_lines,
        'unclassified': unclassified,
        'skipped_topologies': sorted(skipped_topologies),
        'top_subckt_pins': top_pins,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("netlist")
    parser.add_argument("--subckt", default=None, help="which .subckt to decompose if the file has more than one")
    parser.add_argument("--out-dir", default=None, help="default: <netlist_dir>/decomposed")
    parser.add_argument("--topologies", default="current_mirror,differential_pair")
    args = parser.parse_args()

    netlist_path = Path(args.netlist).resolve()
    out_dir = Path(args.out_dir).resolve() if args.out_dir else netlist_path.parent / "decomposed"
    out_dir.mkdir(parents=True, exist_ok=True)
    topologies = set(t.strip() for t in args.topologies.split(","))

    result = decompose(str(netlist_path), args.subckt, topologies)

    print(f"=== Decomposing {netlist_path.name} ===\n")
    for g in result['groups']:
        sp_path = out_dir / f"{g['name']}.sp"
        sp_path.write_text(
            f".subckt {g['name']} {' '.join(g['pins'])}\n" +
            "".join(f"{line}\n" for line in g['body']) +
            f".ends {g['name']}\n"
        )
        print(f"[{g['name']}] devices={g['devices']}")
        print(f"  pins:  {' '.join(g['pins'])}")
        print(f"  wrote  {sp_path}")

    if result['skipped_topologies']:
        print(f"\nDetected but not decomposed (no --topologies match): {', '.join(result['skipped_topologies'])}")
    if result['unclassified']:
        print(f"Unclassified (left as-is at top level): {', '.join(result['unclassified'])}")

    top_out_path = out_dir / netlist_path.name
    include_lines = [f'.include "{g["name"]}.sp"' for g in result['groups']]
    header = "\n".join(include_lines) + ("\n\n" if include_lines else "")
    top_out_path.write_text(header + "\n".join(result['top_level_lines']) + "\n")
    print(f"\n  wrote {top_out_path} (top-level nets unchanged, {len(result['groups'])} group(s) replaced by X-instances)")


if __name__ == "__main__":
    main()
